FROM golang:alpine AS builder

ENV GOPROXY https://goproxy.cn

# 为我们的镜像设置必要的环境变量
ENV GO111MODULE=on \
    CGO_ENABLED=0 \
    GOOS=linux \
    GOARCH=amd64

# 移动到工作目录：/build
WORKDIR /build

# 复制项目中的 go.mod 和 go.sum文件并下载依赖信息
COPY go.mod .
COPY go.sum .
RUN go mod download

# 将代码复制到容器中
COPY . .

# 将我们的代码编译成二进制可执行文件 todolist
RUN go build -o todolist .

EXPOSE 9002
# 需要运行的命令
ENTRYPOINT ["./todolist"]
